## Learning about One Hot Encoding Technique

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
documents = [
    "I love machine learning",
    "I enjoy deep learning",
    "I dislike bugs in my code",
    "I love debugging and fixing issues",
    "I enjoy learning new programming languages"]
    

In [5]:
# Make all the words lowercase and split them into tokens
tokens = [sentence.lower().split() for sentence in documents]
tokens


[['i', 'love', 'machine', 'learning'],
 ['i', 'enjoy', 'deep', 'learning'],
 ['i', 'dislike', 'bugs', 'in', 'my', 'code'],
 ['i', 'love', 'debugging', 'and', 'fixing', 'issues'],
 ['i', 'enjoy', 'learning', 'new', 'programming', 'languages']]

In [ ]:
# convert data above into 2D word to provide to one hot encoder
all_words = [[word] for sentence in tokens for word in sentence]
all_words

[['i'],
 ['love'],
 ['machine'],
 ['learning'],
 ['i'],
 ['enjoy'],
 ['deep'],
 ['learning'],
 ['i'],
 ['dislike'],
 ['bugs'],
 ['in'],
 ['my'],
 ['code'],
 ['i'],
 ['love'],
 ['debugging'],
 ['and'],
 ['fixing'],
 ['issues'],
 ['i'],
 ['enjoy'],
 ['learning'],
 ['new'],
 ['programming'],
 ['languages']]

In [9]:
oh_encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = oh_encoder.fit(all_words)
one_hot_encoded

OneHotEncoder(sparse_output=False)

In [16]:
print("Categories:", oh_encoder.categories_[0])

Categories: ['and' 'bugs' 'code' 'debugging' 'deep' 'dislike' 'enjoy' 'fixing' 'i'
 'in' 'issues' 'languages' 'learning' 'love' 'machine' 'my' 'new'
 'programming']


In [18]:
# Create encoded vectors for each sentence
for sentence in tokens:
    encoded_sentence = oh_encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded_sentence)


Sentence: ['i', 'love', 'machine', 'learning']
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]

Sentence: ['i', 'enjoy', 'deep', 'learning']
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]

Sentence: ['i', 'dislike', 'bugs', 'in', 'my', 'code']
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Sentence: ['i', 'love', 'debugging', 'and', 'fix